name: Build, deploy dev, draft main

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    permissions:
      contents: write
      packages: write
      pull-requests: write
    uses: navikt/dok-workflows/.github/workflows/build-deploy-main.yml@main
    with:
      java-version: '21'
    secrets: inherit
