name: Build, deploy dev feature

on:
  push:
    branches-ignore:
      - main
      - master
      - 'dependabot/**'

jobs:
  build:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: navikt/dok-workflows/.github/workflows/build-deploy-feature-gcp.yml@main
    secrets: inherit