name: Build, deploy dev, draft main

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    permissions:
      contents: write
      packages: write
      pull-requests: write
      id-token: write
    uses: navikt/dok-workflows/.github/workflows/build-deploy-main-gcp.yml@main
    secrets: inherit