#Denne kalles fra appen som vi ønsker å deploye til dev
name: Build, deploy feature

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        description: Java version to build with
        default: '17'
      nav-cluster:
        required: false
        type: string
        description: Nais cluster in dev to deploy to
        default: 'dev-fss'

jobs:
  build-feature:
    uses: navikt/dok-workflows/.github/workflows/wip/2_0_build-app.yml@main
    secrets: inherit
    with:
      java-version: ${{ inputs.java-version }}
  deploy-feature:
    uses: navikt/dok-workflows/.github/workflows/wip/3_0_deploy-all-dev.yml@main
    needs: build-feature
    secrets: inherit
    with:
      image: ${{ needs.build-feature.outputs.image }}
      nav-cluster: ${{ inputs.nav-cluster }}
