name: Build Dependabot PR branch
on:
  push:
    branches:
      - 'dependabot/**'

permissions:
  contents: read
  packages: write

jobs:
  build:
    if: ${{ github.actor == 'dependabot[bot]' }}
    uses: navikt/dok-workflows/.github/workflows/build-app-gar.yml@main
    with:
      java-version: '21'
    secrets: inherit