name: Deploy release to prod

on:
  release:
    types:
      - published

jobs:
  deploy-prod:
    permissions:
      contents: read
      id-token: write
    uses: navikt/dok-workflows/.github/workflows/deploy-prod-gar.yml@main
    secrets: inherit
    # Fjern 'java-version' for å defaulte til '17'
    # Fjern 'nav-cluster' for å defaulte til 'prod-fss'
    with:
      java-version: '21'
      nav-cluster: 'prod-gcp'