name: Label Dependabot PR on successful build
on:
  pull_request:
    types: [opened]
    branches:
      - 'dependabot/**'

jobs:
  label-dependabot-pr:
    permissions:
      repository-projects: read
      pull-requests: write
      contents: read
      id-token: write
      packages: write
    uses: navikt/dok-workflows/.github/workflows/label-dependabot-pr.yml@main
    secrets: inherit
