name: Deploy build-tag to prod

on:
  workflow_call:
    inputs:
      nav-cluster:
        required: false
        type: string
        description: Nais cluster in dev to deploy to
        default: 'prod-fss'

jobs:
  deploy-to-prod:
    uses: navikt/dok-workflows/.github/workflows/3_0_deploy-nais-app.yml@main
    with:
      image: europe-north1-docker.pkg.dev/nais-management-233d/teamdokumenthandtering/${{ github.event.repository.name }}:${{ github.ref_name }}
      nav-cluster: ${{ inputs.nav-cluster }}
      nav-environment: p
    secrets: inherit