name: Automerge Dependabot PRs, build and deploy to dev, and create release draft

on:
  workflow_call:
    inputs:
      ignored-dependencies:
        description: Komma-separert liste over dependencies som ikke skal automerges
        type: string
        required: false
        default: ''
      semver-filter:
        description: Semver filter for hvilke versjoner som kan automerges
        type: string
        required: false
        default: 'patch,minor,unknown'
      always-allow:
        description: Komma-separert liste over dependencies som alltid skal automerges, uavhengig av semver-filter
        type: string
        required: false
        default: ''
      minimum-age-of-pr:
        description: Minimum alder på PR i dager før den automerges
        type: string
        required: false
        default: '5'
      java-version:
        description: Java version som skal brukes til bygging. Utledes om ikke angitt
        type: string
        required: false
        default: ''
      deploy-and-draft-release:
        description: Deploy til dev og lag release draft. Relevant for nais-job apper som ikke skal deployes eller releases
        type: boolean
        required: false
        default: true

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      statuses: read
    outputs:
      merged-pr-count: ${{ steps.automerge.outputs.merged-pr-count }}
    steps:
      - name: Automerge Dependabot PRs
        id: automerge
        uses: navikt/automerge-dependabot@main
        with:
          token: ${{ github.token }}
          minimum-age-of-pr: ${{ inputs.minimum-age-of-pr }}
          blackout-periods: 'Sat,Sun,May 1,May 17,Dec 24-Jan 3'
          ignored-dependencies: ${{ inputs.ignored-dependencies }}
          semver-filter: ${{ inputs.semver-filter }}
          always-allow: ${{ inputs.always-allow }}
      - name: Automerge results
        run: |
          echo "Automerge Resultat:"
          echo "Antall mergede PRer: ${{ steps.automerge.outputs.merged-pr-count }}"