name: Automerge Dependabot PRs, build and deploy to dev, and create release draft

on:
  workflow_call:
    inputs:
      ignored-dependencies:
        description: 'Komma-separert liste over dependencies som ikke skal automerges'
        type: string
        required: false
        default: ''
      semver-filter:
        description: 'Semver filter for hvilke versjoner som kan automerges'
        type: string
        required: false
        default: 'patch,minor'
      always-allow:
        description: 'Komma-separert liste over dependencies som skal automerges, men som ikke bruker semver'
        type: string
        required: false
        default: '*' #Automerge alle ikke-semver oppdateringer
      minimum-age-of-pr:
        description: 'Minimum alder på PR i dager før den automerges'
        type: string
        required: false
        default: '5'
      java-version:
        description: 'Java version to build with'
        type: string
        required: false
        default: ''

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      statuses: read
    outputs:
      merged-pr-count: ${{ steps.automerge.outputs.merged-pr-count }}
    steps:
      - name: Automerge Dependabot PRs
        id: automerge
        uses: navikt/automerge-dependabot@main
        with:
          token: ${{ github.token }}
          minimum-age-of-pr: ${{ github.event.inputs.minimum-age-of-pr }}
          blackout-periods: 'Sat,Sun,May 1,May 17,Dec 24-Jan 3'
          ignored-dependencies: ${{ github.event.inputs.ignored-dependencies }}
          semver-filter: ${{ github.event.inputs.semver-filter }}
          always-allow: ${{ github.event.inputs.always-allow }}

  determine-java-version:
    needs: automerge
    if: needs.automerge.outputs.merged-pr-count > 0 && github.event.inputs.java-version == ''
    runs-on: ubuntu-latest
    outputs:
      java-version: ${{ steps.determine-java-version.outputs.java-version }}
    steps:
      - name: Determine Java version
        id: determine-java-version
        uses: navikt/dok-workflows/.github/workflows/determine-java-version.yml@main

  #Bygger, deployer til dev, og lager release draft
  build-and-deploy:
    needs: determine-java-version
    if: needs.automerge.outputs.merged-pr-count > 0
    uses: navikt/dok-workflows/.github/workflows/build-deploy-main-gar.yml@main
    with:
      java-version: ${{ steps.determine-java-version.outputs.java-version }}
    secrets: inherit
