name: Automerge Dependabot PRs, build and deploy to dev, and create release draft

on:
  workflow_dispatch:
    inputs:
      ignored-dependencies:
        description: 'Komma-separert liste over dependencies som ikke skal automerges'
        required: false
        default: ''
      semver-filter:
        description: 'Semver filter for hvilke versjoner som kan automerges'
        required: false
        default: 'patch,minor'
      always-allow:
        description: 'Komma-separert liste over dependencies som skal automerges, men som ikke bruker semver'
        required: false
        default: '*' #Automerge alle ikke-semver oppdateringer

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      statuses: read
    outputs:
      merged-pr-count: ${{ steps.automerge.outputs.merged-pr-count }}
    steps:
      - name: Automerge Dependabot PRs
        id: automerge
        uses: navikt/automerge-dependabot@main
        with:
          token: ${{ github.token }}
          minimum-age-of-pr: '5'
          blackout-periods: 'Sat,Sun,May 1,May 17,Dec 24-Jan 3'
          ignored-dependencies: ${{ github.event.inputs.ignored-dependencies }}
          semver-filter: ${{ github.event.inputs.semver-filter }}
          always-allow: ${{ github.event.inputs.always-allow }}

  #Bygger, deployer til dev, og lager release draft
  build-and-deploy:
    needs: automerge
    if: needs.automerge.outputs.merged-pr-count > 0
    uses: navigate/dok-workflows/.github/workflows/build-deploy-main-gar.yml
    secrets: inherit
