name: Build and publish artifact

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        description: Java version to build with
        default: '17'

jobs:
  publish-artifact:
    uses: navikt/dok-workflows/.github/workflows/publish-artifact.yml@main
    needs: build-test
    with:
      java-version: ${{ inputs.java-version }}
      build-tag: ${{ github.ref_name }}
    secrets: inherit
