name: Build app

on:
  workflow_call:
    outputs:
      tag:
        description: "Build tag"
        value: ${{ jobs.build-app.outputs.tag }}
      image:
        description: "GAR image"
        value: ${{ jobs.build-app.outputs.image }}
    inputs:
      java-version:
        required: false
        type: string
        description: Java version to build with
        default: '17'

jobs:
  build-app:
    name: Build app
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      tag: ${{ steps.docker-build-push.outputs.tag }}
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      # prebuild
      - name: Checkout code
        uses: actions/checkout@v4
        # checkout gir shallow copy - fetch-depth: 0 vil tilgjengeliggjøre tags
        with:
          fetch-depth: 0
      - name: Set up JDK${{ inputs.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
      - name: Generate ~/.m2/repository cache key
        id: m2-cache-key
        run: echo "keyname=$(date +'maven-week-%U')" >> $GITHUB_OUTPUT
      - name: Cache ~/.m2/repository
        id: cache-m2-repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ steps.m2-cache-key.outputs.keyname }}
      # maven build
      - name: Create m2-settings
        uses: whelk-io/maven-settings-xml-action@7c60eb95b2d5ec18f2e0e29f34c9ed69475e7a96 # v21
        with:
          repositories: '[
            { "id": "central", "url": "https://repo1.maven.org/maven2/", "releases": { "enabled": "true" }, "snapshots": { "enabled": "false" } },
            { "id": "github", "url": "https://maven.pkg.github.com/navikt/maven-release", "releases": { "enabled": "true" }, "snapshots": { "enabled": "false" } },
            { "id": "confluent", "url": "https://packages.confluent.io/maven/" },
            { "id": "jitpack", "url": "https://jitpack.io" }
          ]'
          servers: '[
            { "id": "github", "username": "x-access-token", "password": "${{ secrets.READER_TOKEN }}" }
          ]'
          output_file: settings.xml
      - name: Download toolchain file
        run: |
          curl https://raw.githubusercontent.com/navikt/dok-workflows/main/resources/toolchains.xml --output toolchains.xml
      - name: Set maven artifact version
        run: |
          mvn versions:set -DnewVersion="$( git rev-parse --short HEAD )"
          mvn versions:commit
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots -s settings.xml --global-toolchains toolchains.xml verify
      # docker build
      - name: Build and push to GAR
        if: ${{ github.actor != 'dependabot[bot]' }}
        id: docker-build-push
        uses: nais/docker-build-push@v0
        with:
          team: teamdokumenthandtering
          pull: true
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          byosbom: target/bom.json
