name: Build, deploy feature

on:
  workflow_call:

jobs:
  build-main:
    uses: navikt/dok-workflows/.github/workflows/build-app.yml@main
    secrets: inherit
  deploy-main:
    uses: navikt/dok-workflows/.github/workflows/deploy-all-dev.yml@main
    needs: build-main
    secrets: inherit
    with:
      build-tag: ${{ needs.build-main.outputs.build-tag }}
  draft-release:
    uses: navikt/dok-workflows/.github/workflows/release-draft.yml@main
    needs: build-main
    with:
      build-tag: ${{ needs.build-main.outputs.build-tag }}
