name: Build, deploy feature

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        description: Java version to build with
        default: '17'
      nav-cluster:
        required: false
        type: string
        description: Nais cluster in dev to deploy to
        default: 'dev-fss'

jobs:
  build-feature-fss:
    if: inputs.nav-cluster.endsWith('fss')
    uses: navikt/dok-workflows/.github/workflows/build-app.yml@main
    secrets: inherit
    with:
      java-version: ${{ inputs.java-version }}
  build-feature-gcp:
    if: inputs.nav-cluster.endsWith('gcp')
    uses: navikt/dok-workflows/.github/workflows/build-app-gcp.yml@main
    secrets: inherit
    with:
      java-version: ${{ inputs.java-version }}
  deploy-feature:
    uses: navikt/dok-workflows/.github/workflows/deploy-all-dev.yml@main
    needs: build-feature
    secrets: inherit
    with:
      build-tag: ${{ needs.build-feature.outputs.build-tag }}
      nav-cluster: ${{ inputs.nav-cluster }}
