name: Build, deploy feature

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        description: Java version to build with
        default: '17'
      nav-cluster:
        required: false
        type: string
        description: Nais cluster in p to deploy to
        default: 'dev-fss'

jobs:
  build-main:
    uses: navikt/dok-workflows/.github/workflows/build-app-gar.yml@main
    secrets: inherit
    with:
      java-version: ${{ inputs.java-version }}
  deploy-main:
    uses: navikt/dok-workflows/.github/workflows/deploy-all-dev-gar.yml@main
    needs: build-main
    secrets: inherit
    with:
      image: ${{ needs.build-main.outputs.image }}
      nav-cluster: ${{ inputs.nav-cluster }}
  draft-release:
    uses: navikt/dok-workflows/.github/workflows/release-draft-gar.yml@main
    needs: build-main
    with:
      tag: ${{ needs.build-main.outputs.tag }}
