name: Build, deploy feature to gcp

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        description: Java version to build with
        default: '17'

jobs:
  build-feature-gcp:
    uses: navikt/dok-workflows/.github/workflows/build-app-gcp.yml@main
    secrets: inherit
    with:
      java-version: ${{ inputs.java-version }}
  deploy-feature:
    uses: navikt/dok-workflows/.github/workflows/deploy-all-dev-gcp.yml@main
    needs: build-feature-gcp
    secrets: inherit
    with:
      build-tag: ${{ needs.build-feature-gcp.outputs.build-tag }}
      nav-cluster: dev-gcp
