name: Build and deploy Dependabot PR branch for minor/patch version - merge if sucessful

on:
  workflow_call:

jobs:
  build-deploy:
    if: github.actor == 'dependabot[bot]'
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: navikt/dok-workflows/.github/workflows/build-deploy-feature-gar.yml@main

  merge-branch:
    needs: build-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Merge PR
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
