name: Handle Dependabot PR branch

on:
  workflow_call:

jobs:
  determine-semver-version:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1

  build:
    needs: determine-semver-version
    if: github.actor == 'dependabot[bot]' && needs.determine-semver-version.outputs.update-type == 'version-update:semver-major'
    uses: navikt/dok-workflows/.github/workflows/dependabot-major.yml@main
    secrets: inherit

  build-deploy:
    needs: determine-semver-version
    if: github.actor == 'dependabot[bot]' && needs.determine-semver-version.outputs.update-type != 'version-update:semver-major'
    uses: navikt/dok-workflows/.github/workflows/dependabot-minor-or-patch.yml@main
    secrets: inherit