name: Build Dependabot PR branch for major version

on:
  workflow_call:

jobs:
  build-deploy:
    if: github.actor == 'dependabot[bot]'
    permissions:
      contents: read
      id-token: write
    uses: navikt/dok-workflows/.github/workflows/build-app-gar.yml@main
