on:
  workflow_call:
    inputs:
      build-tag:
        required: true
        type: string
      nav-cluster:
        required: true
        type: string
      nav-environment:
        required: true
        type: string

jobs:
  deploy-nais-app:
    name: Deploy to ${{ inputs.nav-environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # sanity check
      - name: Check if nais/${{ inputs.nav-environment }}-config.json exists
        id: check-json
        run: echo "::set-output name=file-exists::$(test -f nais/${{ inputs.nav-environment }}-config.json && echo 'config_exists' || echo 'config_not_exists')"
      - uses: nais/deploy/actions/deploy@v1
        if: ${{ steps.check-json.outputs.file-exists == 'config_exists' }}
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ inputs.nav-cluster }}
          RESOURCE: nais/naiserator.yaml
          VARS: nais/${{ inputs.nav-environment }}-config.json
          VAR: image=ghcr.io/${{ github.repository }}:${{ inputs.build-tag }}
      - name: Unable to deploy
        if: ${{ steps.check-json.outputs.file-exists != 'config_exists' }}
        run: echo "::warning title=Unable to deploy::Could not find nais/${{ inputs.nav-environment }}-config.json"