name: Deploy build-tag to all environments in dev-fss

on:
  workflow_call:
    inputs:
      build-tag:
        required: true
        type: string

jobs:
  detect-dev-environments:
    name: Detect dev environments to deploy to
    runs-on: ubuntu-latest
    outputs:
      environments: ${{ steps.create-strategy-matrix.outputs.environments }}
    steps:
      - uses: actions/checkout@v3
      - id: create-strategy-matrix
        run: echo "::set-output name=environments::$(array=($(ls nais/q*config.json | sed -nr 's/nais\/(.*)\-config.json/\1/p')); echo ${array[@]})"

  deploy-to-dev:
    uses: navikt/dok-workflows/.github/workflows/deploy-nais-app.yml@main
    needs: detect-dev-environments
    strategy:
      matrix:
        environment: ${{ fromJson(needs.detect-dev-environments.outputs.environments) }}
    with:
      build-tag: ${{ inputs.build-tag }}
      nav-cluster: dev-fss
      nav-environment: ${{ matrix.environment }}
    secrets: inherit