name: Deploy to all environments in dev-fss based on q*-files in the nais folder

on:
  workflow_call:
    inputs:
      IMAGE:
        required: true
        type: string

jobs:
  detect-dev-environments:
    name: Detect dev environments to deploy to
    runs-on: ubuntu-latest
    outputs:
      environments: ${{ steps.create-strategy-matrix.outputs.environments }}
    steps:
      - uses: actions/checkout@v3
      - id: create-strategy-matrix
        run: echo "::set-output name=environments::$(ls nais/q*config.json | jq -R -s -c 'split("\n")[:-1]')"

  deploy-to-dev:
    name: Deploy to dev-fss
    runs-on: ubuntu-latest
    needs: detect-dev-environments
    strategy:
      matrix:
        environment: ${{ fromJson(needs.detect-dev-environments.outputs.environments) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: nais/naiserator.yaml
          VARS: ${{ matrix.environment }}
          VAR: image=${{ inputs.IMAGE }}