name: Deploy build-tag to prod-fss

on:
  workflow_call:

jobs:
  deploy-to-prod:
    uses: navikt/dok-workflows/.github/workflows/deploy-nais-app.yml@main
    with:
      build-tag: ${{ github.ref_name }}
      nav-cluster: prod-fss
      nav-environment: p
    secrets: inherit