name: Build and push

on:
  workflow_call:
    inputs:
      IMAGE:
        required: true
        type: string

jobs:
  deploy-to-prod:
    name: Deploy to prod-fss
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: nais/naiserator.yaml
          VARS: p-config.yaml
          VAR: image=${{ inputs.IMAGE }}