name: Build branch

on:
  workflow_call:

jobs:
  runs-on: ubuntu-latest
  prebuild:
    uses: navikt/dok-workflows/.github/workflows/prebuild.yml@main
  mvnbuild:
    needs: prebuild
    uses: navikt/dok-workflows/.github/workflows/mvnbuild.yml@main
