name: Prebuild title

on:
  workflow_call:

jobs:
  prebuild-in-job:
    name: Prebuild name from name
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'