name: Publish artifact with build-tag to Github package registry

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        description: Java version to build with
        default: '17'

jobs:
  build:
    name: Build and publish artifact to ghcr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create m2-settings
        uses: whelk-io/maven-settings-xml-action@6df64e4ba4842c203c604c1f45246c5863410adb # v21.1
        with:
          repositories: '[
            { "id": "github", "url": "https://maven.pkg.github.com/navikt/maven-release", "releases": { "enabled": "true" }, "snapshots": { "enabled": "false" } },
            { "id": "confluent", "url": "https://packages.confluent.io/maven/" }
          ]'
          servers: '[
            { "id": "github", "username": "x-access-token", "password": "${{ secrets.READER_TOKEN }}" },
            { "id": "ghcr", "username": "${{ github.actor }}", "password": "${{ secrets.GITHUB_TOKEN }}" }
          ]'
          output_file: settings.xml
      - name: Set up JDK${{ inputs.java-version }} and cache dependencies
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Download toolchain file
        run: |
          curl https://raw.githubusercontent.com/navikt/dok-workflows/main/resources/toolchains.xml --output toolchains.xml
      - name: Set release tag
        run: |
          echo "Setting tag ${{ github.ref_name }}"
          mvn versions:set -DnewVersion="${{ github.ref_name }}"
          mvn versions:commit
      - name: Build with Maven
        run: mvn --settings settings.xml --global-toolchains toolchains.xml deploy
