name: Release draft

on:
  workflow_call:
    inputs:
      build-tag:
        required: true
        type: string

jobs:
  create-release-draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@ed4bc48ec97379be2258e7b7ac2624a3e26ab809 # 7.4.0
        with:
          tag: ${{ inputs.build-tag }}
          name: ${{ inputs.build-tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
