name: Test Conditional Logic for merged-pr-count

on:
  workflow_dispatch:
    inputs:
      test-value:
        description: 'Value to test (will be used as merged-pr-count)'
        required: false
        default: '0'

jobs:
  simulate-automerge:
    runs-on: ubuntu-latest
    outputs:
      merged-pr-count: ${{ github.event.inputs.test-value }}
    steps:
      - name: Simulate automerge output
        run: |
          echo "Simulating merged-pr-count output: ${{ github.event.inputs.test-value }}"
          echo "Type check - is it numeric?"
          if [[ "${{ github.event.inputs.test-value }}" =~ ^[0-9]+$ ]]; then
            echo "✅ Value is numeric"
          else
            echo "❌ Value is not numeric"
          fi

  test-greater-than-zero:
    needs: simulate-automerge
    if: needs.simulate-automerge.outputs.merged-pr-count > 0
    runs-on: ubuntu-latest
    steps:
      - name: This job runs if merged-pr-count > 0
        run: |
          echo "✅ SUCCESS: Condition 'merged-pr-count > 0' evaluated to TRUE"
          echo "Value was: ${{ needs.simulate-automerge.outputs.merged-pr-count }}"

  test-not-equal-zero:
    needs: simulate-automerge
    if: needs.simulate-automerge.outputs.merged-pr-count != '0' && needs.simulate-automerge.outputs.merged-pr-count != ''
    runs-on: ubuntu-latest
    steps:
      - name: This job runs if merged-pr-count is not zero or empty
        run: |
          echo "✅ SUCCESS: Condition 'merged-pr-count != 0 and not empty' evaluated to TRUE"
          echo "Value was: ${{ needs.simulate-automerge.outputs.merged-pr-count }}"

  test-results-summary:
    needs: [simulate-automerge, test-greater-than-zero, test-not-equal-zero]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Summary of test results
        run: |
          echo "## Test Results Summary" >> $GITHUB_STEP_SUMMARY
          echo "**Test value:** \`${{ needs.simulate-automerge.outputs.merged-pr-count }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ "${{ needs.test-greater-than-zero.result }}" = "success" ]; then
            echo "✅ **Condition \`> 0\`:** PASSED" >> $GITHUB_STEP_SUMMARY
          elif [ "${{ needs.test-greater-than-zero.result }}" = "skipped" ]; then
            echo "❌ **Condition \`> 0\`:** SKIPPED (evaluated to false)" >> $GITHUB_STEP_SUMMARY
          else
            echo "⚠️ **Condition \`> 0\`:** ${{ needs.test-greater-than-zero.result }}" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ "${{ needs.test-not-equal-zero.result }}" = "success" ]; then
            echo "✅ **Condition \`!= '0' && != ''\`:** PASSED" >> $GITHUB_STEP_SUMMARY
          elif [ "${{ needs.test-not-equal-zero.result }}" = "skipped" ]; then
            echo "❌ **Condition \`!= '0' && != ''\`:** SKIPPED (evaluated to false)" >> $GITHUB_STEP_SUMMARY
          else
            echo "⚠️ **Condition \`!= '0' && != ''\`:** ${{ needs.test-not-equal-zero.result }}" >> $GITHUB_STEP_SUMMARY
          fi
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Test various values:" >> $GITHUB_STEP_SUMMARY
          echo "- \`0\` - Should skip both conditions" >> $GITHUB_STEP_SUMMARY
          echo "- \`'0'\` - Should skip both conditions" >> $GITHUB_STEP_SUMMARY
          echo "- \`1\` - Should pass both conditions" >> $GITHUB_STEP_SUMMARY
          echo "- \`'3'\` - Should pass both conditions" >> $GITHUB_STEP_SUMMARY
          echo "- \`abc\` - Should skip \`> 0\` but might pass \`!= '0'\`" >> $GITHUB_STEP_SUMMARY
          echo "- \`''\` - Should skip both conditions" >> $GITHUB_STEP_SUMMARY
